### ISSUE TITLE
Show bar only when needed

### ISSUE THREAD

**Issue by ClSlaid** [4nkitd/h4ck3r#4]
Not really everyone want to hack every site they see. The bar keep showing on every new site people visit maybe annoying and unnecessary.
![image](https://user-images.githubusercontent.com/44747719/114032714-260cbd80-98af-11eb-9c9b-48219b2264b8.png)
And I don't really know what this is used for, maybe wiki is needed.
BTW, thanks bro, you are doing great.

**Comment by 4nkitd** [comment]
# thanks for the review

# need info bellow

Where did you download the extension from 
- Firefox store
- Edge Store
- Github

which version of extension are you using.
I'll Make the wiki ASAP.

**Comment by 4nkitd** [comment]
added the wiki and the requested condition is added the toolbar will be disabled for all sites.

changes will be reflected version 0.0.8 onwards.

please upgrade from GitHub if required as the review process can take up to a week to release.

# thanks again .
